version: "3.7"

services:
  webserver:
    build:
      context: .
    volumes:
      - ./:/home
    ports:
      - "5000:5000"
    command: flask run --host='0.0.0.0'
    environment:
      FLASK_ENV: development
      PYTHONPATH: .
      FLASK_APP: web/endpoints.py 
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./schema_storages/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
