version: "3.7"

services:
  webserver:
    build:
      context: .
    volumes:
      - ./:/home
    ports:
      - "5000:5000"
    command: flask run --host='0.0.0.0'
    environment:
      FLASK_ENV: development
      PYTHONPATH: .
      FLASK_APP: web/endpoints.py 
  postgres:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./schema_storages/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql
  zookeeper:
    image: wurstmeister/zookeeper
  kafka:
    depends_on:
     - zookeeper
    image: wurstmeister/kafka:0.10.1.0-2
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      # KAFKA_CREATE_TOPICS: "lhama_second_step:1:1"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: 9092
      DOCKER_API_VERSION: 1.22
